/**
 * Portions of these type contracts are derived from Class Variance Authority.
 * Copyright 2022-present Joe Bell and contributors. Licensed under Apache-2.0.
 * Modifications Copyright 2026 Selçuk Çukur / Obvia.
 */

import type { ClassValue } from "../cx/types";

/** Internal variant definition map used by the CV runtime. */
export type VariantShape<T extends ClassValue = ClassValue> = Record<string, Record<string, T>>;

/** Variant keys prefixed with `_` are omitted from public `VariantProps`. */
export type InternalVariantKey = `_${string}`;

/** Converts string boolean keys into ergonomic boolean props. */
export type StringToBoolean<T> = T extends "true" | "false" ? boolean : T;

type OmitUndefined<T> = T extends undefined ? never : T;
type UnionToIntersection<U> = (U extends unknown ? (value: U) => void : never) extends (
  value: infer I,
) => void
  ? I
  : never;

type RightMerge<A, B> = {
  [K in keyof A | keyof B]: K extends keyof B ? B[K] : K extends keyof A ? A[K] : never;
};

/** Runtime selection shape inferred from a variant map. */
export type VariantSelection<V> = {
  [K in keyof V]?: StringToBoolean<keyof V[K]> | undefined;
};

/** Mutually exclusive runtime class override properties. */
export type ClassProp<T extends ClassValue = ClassValue> =
  | { class?: T; className?: never }
  | { class?: never; className?: T };

type CompoundSelection<V> = {
  [K in keyof V]?:
    | StringToBoolean<keyof V[K]>
    | readonly StringToBoolean<keyof V[K]>[]
    | undefined;
};

/** A compound selector plus the class value emitted when it matches. */
export type CompoundVariant<V, T extends ClassValue = ClassValue> =
  CompoundSelection<V> & ClassProp<T>;

/** Callable component generated by `cv`. */
export interface CVComponent<Config, Variants, T extends ClassValue = ClassValue> {
  (
    props?: Variants extends VariantShape
      ? VariantSelection<Variants> & ClassProp<T>
      : ClassProp<T>,
  ): string;
  readonly config: Config;
}

/** Structural component shape used internally for composition. */
export type CVComponentShape = CVComponent<any, any, any>;

type ComposedTuple<
  Single extends CVComponentShape | undefined,
  List extends readonly CVComponentShape[],
> = [Single] extends [CVComponentShape] ? [Single] : List;

type MergedVariants<T extends readonly unknown[]> = UnionToIntersection<
  {
    [K in keyof T]: T[K] extends {
      config: { variants?: infer V extends VariantShape };
    }
      ? V
      : never;
  }[number]
>;

type DefaultsOf<Component> = Component extends {
  config: { defaultVariants?: infer D };
}
  ? D extends undefined
    ? {}
    : D
  : {};

type MergedDefaults<T extends readonly unknown[]> = T extends readonly [
  infer Head,
  ...infer Rest,
]
  ? RightMerge<DefaultsOf<Head>, MergedDefaults<Rest>>
  : {};

type AllVariants<
  Variants,
  Single extends CVComponentShape | undefined,
  List extends readonly CVComponentShape[],
> = [Single] extends [undefined]
  ? [List] extends [readonly []]
    ? Variants
    : Variants & MergedVariants<List>
  : Variants & MergedVariants<ComposedTuple<Single, List>>;

type DefaultsFrom<Config> = Config extends { defaultVariants?: infer D } ? D : {};

/** Authoring contract accepted by `cv`. */
export type CVConfig<
  Config,
  Variants,
  Single extends CVComponentShape | undefined = undefined,
  List extends readonly CVComponentShape[] = [],
  T extends ClassValue = ClassValue,
  Merged = AllVariants<Variants, Single, List>,
> = Config & {
  base?: T;
  variants?: Variants extends Record<string, Record<string, T>>
    ? Variants & { __proto__?: never }
    : never;
  composes?: Single | readonly [...List];
} & ([keyof Merged] extends [never]
    ? { defaultVariants?: never; compoundVariants?: never }
    : {
        defaultVariants?: VariantSelection<Merged>;
        compoundVariants?: readonly CompoundVariant<Merged, T>[];
      });

/** Factory signature implemented by `cv`. */
export interface CV<T extends ClassValue = ClassValue> {
  <
    Config,
    Variants,
    Single extends CVComponentShape | undefined = undefined,
    List extends readonly CVComponentShape[] = [],
  >(
    config: CVConfig<Config, Variants, Single, List, T>,
  ): CVComponent<
    Omit<Config, "defaultVariants"> & {
      variants: AllVariants<Variants, Single, List>;
      defaultVariants: Omit<
        MergedDefaults<ComposedTuple<Single, List>>,
        keyof DefaultsFrom<Config>
      > & DefaultsFrom<Config>;
    },
    AllVariants<Variants, Single, List>,
    T
  >;
}

/**
 * Extracts the public variant selection props from a component created by
 * `cv`, excluding class overrides and variants intentionally marked internal.
 */
export type VariantProps<Component extends (...args: any) => any> = Omit<
  OmitUndefined<Parameters<Component>[0]>,
  "class" | "className" | InternalVariantKey
>;
